services:
  laravel-demo:
    image: clean-structure/laravel-demo:0.1
    restart: unless-stopped
    build:
      context: docker/php
      target: php-dev
      args:
        - UID=${UID}
        - GID=${GID}
    volumes:
      - ./backend:/var/www/backend/
      - ./backend/storage/phpunit:/opt/phpstorm-coverage
    ports:
      - "8084:80"
    healthcheck:
      test: curl --fail http://localhost:80/healthcheck || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s