services:
  php-dev:
    image: clean-architecture/laravel-demo-structure:0.1
    restart: unless-stopped
    build:
      context: docker
      target: php-dev
      args:
        - UID=${UID}
        - GID=${GID}
    volumes:
      - ./backend:/var/www/backend/
    ports:
      - "8084:80"
    healthcheck:
      test: curl --fail http://localhost:80/healthcheck || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s