services:
  wiki:
    image: clean-structure/doc:0.1
    restart: unless-stopped
    build:
      context: docker/node
      target: node22
      args:
        - UID=${UID}
        - GID=${GID}
    volumes:
      - ./doc:/var/www/frontend
    ports:
      - "5173:5173"
    command: sh -c 'yarn install && yarn docs:dev'